import {useEffect,useRef,useState} from 'react';
import {ConversationManager,runCommand} from '../../ai/chat';
import {buildPrompt} from '../../ai/prompts';
import {AlwaysListener} from '../../audio/alwaysListening';

type MicMode='always'|'push-to-talk'|'off';
type Attachment={name:string;path:string;size:number;type:string;text?:string;dataBase64?:string};
type Message={id?:number;role:'user'|'assistant';content:string;created_at?:string;attachments?:Attachment[]};

async function decodeSpeechBlob(blob:Blob){
 const ctx=new AudioContext({sampleRate:16000});
 try{const decoded=await ctx.decodeAudioData(await blob.arrayBuffer());const mono=new Float32Array(decoded.length);for(let ch=0;ch<decoded.numberOfChannels;ch++){const d=decoded.getChannelData(ch);for(let i=0;i<decoded.length;i++)mono[i]+=d[i]/decoded.numberOfChannels}return{samples:mono,sampleRate:decoded.sampleRate}}
 finally{await ctx.close().catch(()=>{})}
}

export function Chat(){
 const[open,setOpen]=useState(false),[text,setText]=useState(''),[answer,setAnswer]=useState(''),[speechText,setSpeechText]=useState(''),[listening,setListening]=useState(false),[error,setError]=useState(''),[micMode,setMicMode]=useState<MicMode|null>(null),[showSpeech,setShowSpeech]=useState(false),[messages,setMessages]=useState<Message[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[sending,setSending]=useState(false);
 const listener=useRef<AlwaysListener|null>(null),pttDown=useRef(false),bubbleTimer=useRef<number|undefined>(undefined),initialized=useRef(false);

 const refreshHistory=async()=>{try{setMessages(await window.electronAPI.getChatHistory(100))}catch(e){setError(String(e))}};
 const showBubble=(value:string)=>{setAnswer(value);if(bubbleTimer.current)window.clearTimeout(bubbleTimer.current);bubbleTimer.current=window.setTimeout(()=>setAnswer(''),6500)};
 async function speakOnce(t:string){if(!t.trim())return;try{const settings=await window.electronAPI.getSettings();if(settings?.config?.speakResponses===false)return;const b=await window.electronAPI.speak(t);const raw=atob(b);const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const mime=settings?.config?.ttsProvider==='local'?'audio/wav':'audio/mpeg';const u=URL.createObjectURL(new Blob([bytes],{type:mime})),a=new Audio(u);await a.play();await new Promise(r=>{a.onended=()=>r(null);a.onerror=()=>r(null)});URL.revokeObjectURL(u)}catch(e){setError('Voice response error: '+String(e))}}
 async function send(q=text){const question=q.trim();if((!question&&!attachments.length)||sending)return;setSending(true);setText('');setError('');const outgoing=[...attachments];setAttachments([]);try{if(question&&await runCommand(question)){await window.electronAPI.saveChatMessage('user',question,outgoing);await refreshHistory();return}const tool=question?await window.electronAPI.assistantTool(question):'';if(tool){await window.electronAPI.saveChatMessage('user',question,outgoing);await window.electronAPI.saveChatMessage('assistant',tool);showBubble(tool);await refreshHistory();await speakOnce(tool);return}const manager=new ConversationManager();let full='';await manager.run(buildPrompt(question,[],outgoing),d=>{full+=d;showBubble(full)});if(full.trim()){await refreshHistory();await speakOnce(full)}}catch(e){setError(String(e))}finally{setSending(false)}}
 async function handleUtterance(b:Blob){setListening(true);try{const webm=await b.arrayBuffer(),decoded=await decodeSpeechBlob(b);const q=await window.electronAPI.transcribe({webm,samples:decoded.samples,sampleRate:decoded.sampleRate});if(q.trim()){if(showSpeech){setSpeechText(q);window.setTimeout(()=>setSpeechText(''),5000)}await send(q)}}catch(e){setError('Speech recognition error: '+String(e))}finally{setListening(false)}}
 async function stopListener(){listener.current?.stop();listener.current=null;setListening(false);pttDown.current=false}
 async function startAlways(){await stopListener();if(micMode!=='always')return;try{const l=new AlwaysListener();listener.current=l;await l.start(handleUtterance)}catch(e){setError('Microphone permission error: '+String(e))}}
 async function pushStart(){if(micMode!=='push-to-talk'||listener.current||sending)return;try{const l=new AlwaysListener();listener.current=l;pttDown.current=true;setListening(true);await l.startManual(handleUtterance)}catch(e){pttDown.current=false;setListening(false);setError('Microphone permission error: '+String(e))}}
 function pushStop(){if(micMode==='push-to-talk'&&listener.current){listener.current.stopManual();listener.current.stop();listener.current=null;pttDown.current=false;setListening(false)}}
 useEffect(()=>{window.electronAPI.getSettings().then(async x=>{const m=(x.config?.micMode||(x.config?.alwaysListening===false?'off':'always')) as MicMode;setMicMode(m);setShowSpeech(Boolean(x.config?.showSpeechText));initialized.current=true;await refreshHistory()});const a=window.electronAPI.onOpenChat(()=>setOpen(true));const b=window.electronAPI.onMicMode(m=>setMicMode(m));const c=window.electronAPI.onTrayMicMode(m=>{setMicMode(m);void window.electronAPI.setMicMode(m)});return()=>{a();b();c();void stopListener();if(bubbleTimer.current)window.clearTimeout(bubbleTimer.current)}},[]);
 useEffect(()=>{if(!initialized.current||micMode===null)return;if(micMode==='always')void startAlways();else void stopListener()},[micMode]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{if(e.code==='Space'&&micMode==='push-to-talk'&&!(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)){e.preventDefault();if(!pttDown.current)void pushStart()}};const u=(e:KeyboardEvent)=>{if(e.code==='Space'&&pttDown.current){e.preventDefault();pushStop()}};window.addEventListener('keydown',d);window.addEventListener('keyup',u);return()=>{window.removeEventListener('keydown',d);window.removeEventListener('keyup',u)}},[micMode]);
 async function addFiles(){try{const picked=await window.electronAPI.pickAttachments();if(picked.length)setAttachments(v=>[...v,...picked])}catch(e){setError('Attachment error: '+String(e))}}
 const ptt=micMode==='push-to-talk'?<button className={pttDown.current?'ptt active':'ptt'} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);void pushStart()}} onPointerUp={e=>{e.preventDefault();pushStop()}} onPointerCancel={pushStop} title="Hold to talk">🎙</button>:null;
 const history=messages.map((m,i)=><div key={m.id??i} className={'msg '+m.role}><div>{m.content}</div>{m.attachments?.length?<div className="attachments">{m.attachments.map(a=><span key={a.path}>{a.name}</span>)}</div>:null}</div>);
 const panel=<div className="chat"><div className="chatHeader"><span>Chat with Saeed</span><div><button onClick={()=>void window.electronAPI.clearChatHistory().then(refreshHistory)} title="Clear history">🗑</button><button onClick={()=>setOpen(false)}>×</button></div></div><div className="listen">{micMode==='off'?'○ Mic closed':micMode==='push-to-talk'?(listening?'● Recording — release':'○ Hold 🎙 to talk'):(listening?'● Listening':'○ Mic ready')}</div><div className="history">{history.length?history:<div className="empty">Conversation history will stay here.</div>}{sending&&<div className="msg assistant typing">Saeed is thinking…</div>}</div>{showSpeech&&speechText&&<div className="speechText"><span>You said</span><div>{speechText}</div></div>}{error&&<div className="error">{error}</div>}{attachments.length>0&&<div className="pendingAttachments">{attachments.map(a=><span key={a.path}>{a.name} <button onClick={()=>setAttachments(v=>v.filter(x=>x.path!==a.path))}>×</button></span>)}</div>}<div className="row"><button onClick={()=>void addFiles()} title="Attach files or folders">📎</button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void send()} placeholder="Talk to Saeed..." disabled={sending}/>{ptt}<button onClick={()=>void send()} disabled={sending}>Send</button></div><div className="chatTools"><button onClick={()=>setShowSpeech(v=>{const n=!v;setSpeechText('');void window.electronAPI.getSettings().then(x=>window.electronAPI.saveSettings({...x.config,showSpeechText:n}));return n})}>{showSpeech?'Hide speech text':'Show speech text'}</button>{micMode==='off'?<button onClick={()=>void window.electronAPI.setMicMode('always')}>Always listening</button>:<button onClick={()=>void window.electronAPI.setMicMode('off')}>Close mic</button>}</div></div>;
 if(!open)return <>{answer&&<div className="saeedSpeechBubble">{answer}</div>}<button className="chatToggle" onClick={()=>setOpen(true)} title="Start chat">💬</button></>;
 return <>{answer&&<div className="saeedSpeechBubble">{answer}</div>}{panel}</>;
}