import {app,BrowserWindow,dialog,ipcMain,shell,Menu,Tray,nativeImage} from 'electron';import path from 'node:path';import fs from 'node:fs';import {fileURLToPath} from 'node:url';import {createCompanionWindow,revealCompanionWindow} from './windows/companionWindow.js';import {Database} from './services/database.js';import {Credentials} from './services/credentials.js';import {testLLM,streamLLM,testSTTOpenAI,transcribeOpenAI,transcribeOffline,offlineBrain,synthesizeOffline,synthesizeOpenAI,synthesizeAzure,testTTS} from './services/providers.js';import {setupUpdater,check as checkUpdates,install as installUpdate,current as updateState} from './services/updater.js';

function keyFor(provider:string,kind:'llm'|'stt'|'tts'='llm'){
  if(kind==='stt')return provider==='openai'?'openaiSttApiKey':provider+'SttApiKey';
  if(kind==='tts')return provider==='azure'?'azureTtsApiKey':provider==='openai'?'openaiTtsApiKey':provider+'TtsApiKey';
  const map:Record<string,string>={openai:'openaiApiKey',anthropic:'anthropicApiKey',gemini:'geminiApiKey','openai-compatible':'openaiCompatibleApiKey'};
  return map[provider]??(provider+'ApiKey');
}
const __dirname=path.dirname(fileURLToPath(import.meta.url));let win:BrowserWindow|null=null;let db:Database|null=null;let creds:Credentials|null=null;let tray:Tray|null=null;const gotTheLock=app.requestSingleInstanceLock();if(!gotTheLock){app.quit()}else{app.on('second-instance',()=>{if(win&&!win.isDestroyed())revealCompanionWindow(win)});app.whenReady().then(()=>{db=new Database(path.join(app.getPath('userData'),'memory.sqlite3'));creds=new Credentials(db);app.setAppUserModelId('com.saeed.desktop');win=createCompanionWindow(__dirname);setupUpdater(win);const iconPath=path.join(process.resourcesPath,'icons','saeed.png');const icon=fs.existsSync(iconPath)?nativeImage.createFromPath(iconPath):nativeImage.createEmpty();tray=new Tray(icon);tray.setToolTip('Saeed');const show=()=>{if(win&&!win.isDestroyed())revealCompanionWindow(win)};const openSettings=()=>{show();if(win&&!win.webContents.isDestroyed())win.webContents.send('ui:open-settings')};const rebuildMenu=()=>{const mode=(db!.getSetting('settings')||{}).brainMode||'auto';tray?.setContextMenu(Menu.buildFromTemplate([{label:'Show Saeed',click:show},{type:'separator'},{label:'Settings',click:openSettings},{label:'Brain mode',submenu:[{label:'Auto — External LLM then Local fallback',type:'radio',checked:mode==='auto',click:()=>setBrainMode('auto')},{label:'Local brain only',type:'radio',checked:mode==='local',click:()=>setBrainMode('local')},{label:'External LLM only',type:'radio',checked:mode==='api',click:()=>setBrainMode('api')}]},{type:'separator'},{label:'Quit Saeed',click:()=>app.quit()}]))};const setBrainMode=(mode:string)=>{const cfg=db!.getSetting('settings')||{};const m=['auto','local','api'].includes(mode)?mode:'auto';db!.setSetting('settings',{...cfg,brainMode:m});rebuildMenu();if(win&&!win.webContents.isDestroyed())win.webContents.send('settings:brain-mode',m)};rebuildMenu();

ipcMain.handle('avatar:load-model',()=>{const custom=path.join(app.getPath('userData'),'character.vrm');const candidates=[custom,path.join(process.resourcesPath,'models','saeed.vrm'),path.join(app.getAppPath(),'dist','models','saeed.vrm'),path.join(app.getAppPath(),'public','models','saeed.vrm'),path.join(__dirname,'../dist/models/saeed.vrm')];for(const p of candidates){if(fs.existsSync(p))return fs.readFileSync(p)}throw new Error('Saeed VRM asset not found. Checked: '+candidates.join(' | '))});
ipcMain.handle('avatar:choose-model',async()=>{const result=await dialog.showOpenDialog(win??BrowserWindow.getAllWindows()[0],{title:'Choose Saeed Character',properties:['openFile'],filters:[{name:'VRM Character',extensions:['vrm']}]});if(result.canceled||!result.filePaths[0])return{changed:false};const source=result.filePaths[0],destination=path.join(app.getPath('userData'),'character.vrm');fs.copyFileSync(source,destination);if(win&&!win.isDestroyed()&&!win.webContents.isDestroyed())win.webContents.send('avatar:model-changed');return{changed:true,path:destination}});

ipcMain.handle('settings:get',()=>({config:db!.getSetting('settings')??{},hasSecrets:{openai:Boolean(creds!.get(keyFor('openai'))),anthropic:Boolean(creds!.get(keyFor('anthropic'))),gemini:Boolean(creds!.get(keyFor('gemini'))),'openai-compatible':Boolean(creds!.get(keyFor('openai-compatible'))),'openai-stt':Boolean(creds!.get(keyFor('openai','stt'))||creds!.get(keyFor('openai'))),'openai-tts':Boolean(creds!.get(keyFor('openai','tts'))||creds!.get(keyFor('openai'))),azure:Boolean(creds!.get(keyFor('azure','tts')))}}));
ipcMain.handle('settings:save',(_,v:any)=>{const{secrets,...safe}=v||{};db!.setSetting('settings',safe);for(const[k,val]of Object.entries(secrets||{})){if(typeof val==='string'&&val.trim()){const parts=String(k).split(':');const provider=parts[0];const kind=(parts[1]||'llm') as 'llm'|'stt'|'tts';creds!.set(keyFor(provider,kind),val)}}rebuildMenu();return true});
ipcMain.handle('settings:brain-mode',(_,mode:string)=>{setBrainMode(mode);return(db!.getSetting('settings')||{}).brainMode});
ipcMain.handle('settings:clear-secrets',(_,scope:'all'|'llm'|'stt'|'tts'='all')=>{const keys:[string,'llm'|'stt'|'tts'][]=[['openai','llm'],['anthropic','llm'],['gemini','llm'],['openai-compatible','llm'],['openai','stt'],['openai','tts'],['azure','tts']];for(const[p,k]of keys)if(scope==='all'||scope===k)creds!.remove(keyFor(p,k));return true});
ipcMain.handle('window:move-by',(_,dx:number,dy:number)=>{if(!win||win.isDestroyed())return false;const [x,y]=win.getPosition();win.setPosition(Math.round(x+dx),Math.round(y+dy),false);return true});

ipcMain.handle('provider:test',async(_,v:any)=>{const p=v.provider;if(v.kind==='stt'){if(p==='local')return{provider:p,status:'connected',message:'Local Whisper is selected; it is tested when the microphone transcribes.'};const k=creds!.get(keyFor(p,'stt'))||creds!.get(keyFor(p,'llm'));if(p==='openai'){if(!k)return{provider:p,status:'not-configured',message:'OpenAI STT key is not configured'};return testSTTOpenAI(k)}return{provider:p,status:'error',message:'This STT provider is not implemented yet.'}}if(v.kind==='tts'){if(p==='local')return testTTS('local',null,v.config||{},v.modelRoot);const k=creds!.get(keyFor(p,'tts'))||creds!.get(keyFor(p,'llm'));if(p==='azure'||p==='openai')return testTTS(p,k,v.config||{},v.modelRoot);return{provider:p,status:'error',message:'This TTS provider is not implemented yet.'}}const k=creds!.get(keyFor(p,'llm'));return testLLM(p,v.config||{},k)});

ipcMain.handle('chat:send',async(e,req:any)=>{const cfg=db!.getSetting('settings')||{};const mode=cfg.brainMode||'auto';const p=cfg.llmProvider||'openai';const key=creds!.get(keyFor(p,'llm'));const askLocal=()=>offlineBrain(String(req?.userMessage||''));if(mode==='local'){const local=askLocal();if(local){e.sender.send('chat:delta',local);e.sender.send('chat:done',local);return local}throw new Error('The local brain does not know this request yet.')};if(!key){if(mode==='api')throw new Error('No API key configured for the selected external LLM provider.');const local=askLocal();if(local){e.sender.send('chat:delta',local);e.sender.send('chat:done',local);return local}throw new Error('No API key configured and the local brain does not know this request yet.')};try{let full='';for await(const d of streamLLM(p,cfg.llm||{},key,req)){full+=d;e.sender.send('chat:delta',d)}e.sender.send('chat:done',full);return full}catch(error){if(mode!=='api'){const local=askLocal();if(local){e.sender.send('chat:delta',local);e.sender.send('chat:done',local);return local}}throw error}});

ipcMain.handle('audio:transcribe',async(_,input:any)=>{const cfg=db!.getSetting('settings')||{};const p=cfg.sttProvider||'local';if(p==='openai'){const key=creds!.get(keyFor('openai','stt'))||creds!.get(keyFor('openai','llm'));if(!key)throw new Error('OpenAI STT is selected but no STT/LLM OpenAI key is configured.');if(!input?.webm)throw new Error('No microphone audio was received.');return transcribeOpenAI(Buffer.from(input.webm),key,cfg.sttModel||'gpt-4o-mini-transcribe',cfg.language||undefined)}if(!input?.samples)throw new Error('No decoded microphone audio was received.');const language=cfg.sttLanguage||cfg.language||'auto';const candidates=[path.join(process.resourcesPath,'models','offline-stt','sherpa-onnx-whisper-tiny'),path.join(app.getAppPath(),'dist','models','offline-stt','sherpa-onnx-whisper-tiny'),path.join(app.getAppPath(),'public','models','offline-stt','sherpa-onnx-whisper-tiny'),path.join(__dirname,'../dist/models/offline-stt/sherpa-onnx-whisper-tiny')];const modelRoot=candidates.find(p=>fs.existsSync(path.join(p,'tiny-encoder.int8.onnx')))??candidates[0];return transcribeOffline(input.samples instanceof Float32Array?input.samples:new Float32Array(input.samples),Number(input.sampleRate)||16000,modelRoot,language)});

ipcMain.handle('audio:speak',async(_,text:string)=>{const cfg=db!.getSetting('settings')||{};const p=cfg.ttsProvider||'local';const candidates=[path.join(process.resourcesPath,'models','offline-tts','vits-piper-en_US-lessac-medium'),path.join(app.getAppPath(),'dist','models','offline-tts','vits-piper-en_US-lessac-medium'),path.join(app.getAppPath(),'public','models','offline-tts','vits-piper-en_US-lessac-medium'),path.join(__dirname,'../dist/models/offline-tts/vits-piper-en_US-lessac-medium')];const modelRoot=candidates.find(x=>fs.existsSync(path.join(x,'en_US-lessac-medium.onnx')))??candidates[0];let audio:Buffer;if(p==='local')audio=await synthesizeOffline(text,modelRoot,cfg.tts||{});else{const provider=p==='azure'?'azure':'openai';const key=creds!.get(keyFor(provider,'tts'))||creds!.get(keyFor(provider,'llm'));if(!key)throw new Error('TTS credential is not configured for '+provider);audio=provider==='azure'?await synthesizeAzure(text,key,cfg.tts||{}):await synthesizeOpenAI(text,key,cfg.tts||{})}return audio.toString('base64')});

ipcMain.handle('update:check',()=>checkUpdates());ipcMain.handle('update:install',()=>installUpdate());ipcMain.handle('update:state',()=>updateState());ipcMain.handle('system:toggle-clickthrough',(_,v)=>{win?.setIgnoreMouseEvents(Boolean(v),{forward:true});return true});ipcMain.handle('system:open',async(_,target:string)=>{const t=String(target||'').trim();if(/^my computer$/i.test(t)||/^this pc$/i.test(t))return shell.openPath('C:\\');if(/^[a-zA-Z]:[\\/]/.test(t))return shell.openPath(t);return shell.openPath(path.join(app.getPath('home'),t.replace(/^~[\\/]?/,'')))});app.on('activate',()=>{if(!win||win.isDestroyed())win=createCompanionWindow(__dirname);else revealCompanionWindow(win)})})}app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
