import {contextBridge,ipcRenderer} from 'electron';
contextBridge.exposeInMainWorld('electronAPI',{
  loadAvatarModel:()=>ipcRenderer.invoke('avatar:load-model'),
  changeAvatarModel:()=>ipcRenderer.invoke('avatar:choose-model'),
  getSettings:()=>ipcRenderer.invoke('settings:get'),
  saveSettings:(v:unknown)=>ipcRenderer.invoke('settings:save',v),
  testProvider:(v:unknown)=>ipcRenderer.invoke('provider:test',v),
  sendChat:(v:unknown)=>ipcRenderer.invoke('chat:send',v),
  getChatHistory:(limit=100)=>ipcRenderer.invoke('chat:history',limit),
  saveChatMessage:(role:'user'|'assistant',content:string,attachments:any[]=[])=>ipcRenderer.invoke('chat:save-message',role,content,attachments),
  clearChatHistory:()=>ipcRenderer.invoke('chat:clear-history'),
  pickAttachments:()=>ipcRenderer.invoke('files:pick-attachments'),
  transcribe:(v:{webm:ArrayBuffer;samples:Float32Array;sampleRate:number})=>ipcRenderer.invoke('audio:transcribe',v),
  speak:(t:string)=>ipcRenderer.invoke('audio:speak',t),
  realtimeStart:(options:any={})=>ipcRenderer.invoke('realtime:start',options),
  realtimeAudio:(base64:string)=>ipcRenderer.invoke('realtime:audio',base64),
  realtimeStop:()=>ipcRenderer.invoke('realtime:stop'),
  realtimeCancel:()=>ipcRenderer.invoke('realtime:cancel'),
  checkForUpdates:()=>ipcRenderer.invoke('update:check'),
  installUpdate:()=>ipcRenderer.invoke('update:install'),
  getUpdateState:()=>ipcRenderer.invoke('update:state'),
  setClickThrough:(v:boolean)=>ipcRenderer.invoke('system:toggle-clickthrough',v),
  assistantTool:(q:string)=>ipcRenderer.invoke('assistant:tool',q),
  openPath:(p:string)=>ipcRenderer.invoke('system:open',p),
  setBrainMode:(v:'auto'|'local'|'api')=>ipcRenderer.invoke('settings:brain-mode',v),
  setMicMode:(v:'always'|'push-to-talk'|'off')=>ipcRenderer.invoke('settings:mic-mode',v),
  clearApiKeys:(scope:'all'|'llm'|'stt'|'tts'='all')=>ipcRenderer.invoke('settings:clear-secrets',scope),
  moveWindowBy:(dx:number,dy:number)=>ipcRenderer.invoke('window:move-by',dx,dy),
  closeSettingsWindow:()=>ipcRenderer.invoke('settings:close-window'),
  onRealtimeState:(cb:(state:'connecting'|'connected'|'disconnected'|'error',message?:string)=>void)=>{const f=(_:unknown,state:any,message?:string)=>cb(state,message);ipcRenderer.on('realtime:state',f);return()=>ipcRenderer.removeListener('realtime:state',f)},
  onRealtimeAudio:(cb:(base64:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:audio',f);return()=>ipcRenderer.removeListener('realtime:audio',f)},
  onRealtimeUserDelta:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:user-delta',f);return()=>ipcRenderer.removeListener('realtime:user-delta',f)},
  onRealtimeUserFinal:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:user-final',f);return()=>ipcRenderer.removeListener('realtime:user-final',f)},
  onRealtimeAssistantDelta:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:assistant-delta',f);return()=>ipcRenderer.removeListener('realtime:assistant-delta',f)},
  onRealtimeAssistantFinal:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:assistant-final',f);return()=>ipcRenderer.removeListener('realtime:assistant-final',f)},
  onRealtimeDone:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:done',f);return()=>ipcRenderer.removeListener('realtime:done',f)},
  onRealtimeError:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('realtime:error',f);return()=>ipcRenderer.removeListener('realtime:error',f)},
  onChatDelta:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('chat:delta',f);return()=>ipcRenderer.removeListener('chat:delta',f)},
  onUpdate:(cb:(s:any)=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('update:status',f);return()=>ipcRenderer.removeListener('update:status',f)},
  onOpenSettings:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:open-settings',f);return()=>ipcRenderer.removeListener('ui:open-settings',f)},
  onOpenChat:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:open-chat',f);return()=>ipcRenderer.removeListener('ui:open-chat',f)},
  onMicMode:(cb:(s:'always'|'push-to-talk'|'off')=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('settings:mic-mode',f);return()=>ipcRenderer.removeListener('settings:mic-mode',f)},
  onTrayMicMode:(cb:(s:'always'|'push-to-talk'|'off')=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('tray:mic-mode',f);return()=>ipcRenderer.removeListener('tray:mic-mode',f)},
  onChangeCharacter:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:change-character',f);return()=>ipcRenderer.removeListener('ui:change-character',f)},
  onAvatarChanged:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('avatar:model-changed',f);return()=>ipcRenderer.removeListener('avatar:model-changed',f)}
});