import {contextBridge,ipcRenderer} from 'electron';
contextBridge.exposeInMainWorld('electronAPI',{
  loadAvatarModel:()=>ipcRenderer.invoke('avatar:load-model'),
  changeAvatarModel:()=>ipcRenderer.invoke('avatar:choose-model'),
  getSettings:()=>ipcRenderer.invoke('settings:get'),
  saveSettings:(v:unknown)=>ipcRenderer.invoke('settings:save',v),
  testProvider:(v:unknown)=>ipcRenderer.invoke('provider:test',v),
  sendChat:(v:unknown)=>ipcRenderer.invoke('chat:send',v),
  transcribe:(v:{webm:ArrayBuffer;samples:Float32Array;sampleRate:number})=>ipcRenderer.invoke('audio:transcribe',v),
  speak:(t:string)=>ipcRenderer.invoke('audio:speak',t),
  checkForUpdates:()=>ipcRenderer.invoke('update:check'),
  installUpdate:()=>ipcRenderer.invoke('update:install'),
  getUpdateState:()=>ipcRenderer.invoke('update:state'),
  setClickThrough:(v:boolean)=>ipcRenderer.invoke('system:toggle-clickthrough',v),
  openPath:(p:string)=>ipcRenderer.invoke('system:open',p),
  setBrainMode:(v:'auto'|'local'|'api')=>ipcRenderer.invoke('settings:brain-mode',v),
  setMicMode:(v:'always'|'push-to-talk'|'off')=>ipcRenderer.invoke('settings:mic-mode',v),
  clearApiKeys:(scope:'all'|'llm'|'stt'|'tts'='all')=>ipcRenderer.invoke('settings:clear-secrets',scope),
  moveWindowBy:(dx:number,dy:number)=>ipcRenderer.invoke('window:move-by',dx,dy),
  closeSettingsWindow:()=>ipcRenderer.invoke('settings:close-window'),
  onChatDelta:(cb:(s:string)=>void)=>{const f=(_:unknown,s:string)=>cb(s);ipcRenderer.on('chat:delta',f);return()=>ipcRenderer.removeListener('chat:delta',f)},
  onUpdate:(cb:(s:any)=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('update:status',f);return()=>ipcRenderer.removeListener('update:status',f)},
  onOpenSettings:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:open-settings',f);return()=>ipcRenderer.removeListener('ui:open-settings',f)},
  onOpenChat:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:open-chat',f);return()=>ipcRenderer.removeListener('ui:open-chat',f)},
  onMicMode:(cb:(s:'always'|'push-to-talk'|'off')=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('settings:mic-mode',f);return()=>ipcRenderer.removeListener('settings:mic-mode',f)},
  onTrayMicMode:(cb:(s:'always'|'push-to-talk'|'off')=>void)=>{const f=(_:unknown,s:any)=>cb(s);ipcRenderer.on('tray:mic-mode',f);return()=>ipcRenderer.removeListener('tray:mic-mode',f)},
  onChangeCharacter:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('ui:change-character',f);return()=>ipcRenderer.removeListener('ui:change-character',f)},
  onAvatarChanged:(cb:()=>void)=>{const f=()=>cb();ipcRenderer.on('avatar:model-changed',f);return()=>ipcRenderer.removeListener('avatar:model-changed',f)}
});