import {useEffect,useState} from 'react';
type S={llmProvider:string;llm:any;sttModel:string;ttsProvider:string;tts:any;language:string;alwaysListening:boolean};
const defaults:S={llmProvider:'openai',llm:{model:'gpt-5'},sttModel:'gpt-4o-mini-transcribe',ttsProvider:'openai',tts:{model:'gpt-4o-mini-tts',voice:'alloy'},language:'en',alwaysListening:true};
const providers=[['openai','OpenAI / GPT'],['anthropic','Anthropic / Claude'],['gemini','Google / Gemini'],['openai-compatible','OpenAI-compatible']];
export function Settings(){const[open,setOpen]=useState(false);const[s,setS]=useState<S>(defaults);const[has,setHas]=useState<any>({});const[llmKey,setLlmKey]=useState('');const[ttsKey,setTtsKey]=useState('');const[status,setStatus]=useState<any>({});
useEffect(()=>{window.electronAPI.getSettings().then(x=>{setS({...defaults,...x.config,llm:{...defaults.llm,...x.config?.llm},tts:{...defaults.tts,...x.config?.tts}});setHas(x.hasSecrets||{})})},[]);
async function save(){const secrets:any={};if(llmKey.trim())secrets[s.llmProvider]=llmKey;if(ttsKey.trim())secrets[s.ttsProvider==='azure'?'azure':'openai']=ttsKey;await window.electronAPI.saveSettings({...s,secrets});setLlmKey('');setTtsKey('');setHas((x:any)=>({...x,...Object.fromEntries(Object.keys(secrets).map(k=>[k,true]))}))}
async function testLLM(){const r=await window.electronAPI.testProvider({provider:s.llmProvider,config:s.llm});setStatus((x:any)=>({...x,llm:r}))}
async function testTTS(){const p=s.ttsProvider==='azure'?'azure':'openai-tts';const r=await window.electronAPI.testProvider({provider:p,config:s.tts});setStatus((x:any)=>({...x,tts:r}))}
return <><button className="settingsButton" onClick={()=>setOpen(!open)}>⚙ Settings</button>{open&&<div className="settingsPanel"><h3>Saeed AI providers</h3><label>LLM provider<select value={s.llmProvider} onChange={e=>setS({...s,llmProvider:e.target.value})}>{providers.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Model<input value={s.llm.model} onChange={e=>setS({...s,llm:{...s.llm,model:e.target.value}})}/></label>{s.llmProvider==='openai-compatible'&&<label>Base URL<input placeholder="https://provider.example/v1" value={s.llm.baseUrl||''} onChange={e=>setS({...s,llm:{...s.llm,baseUrl:e.target.value}})}/></label>}<label>LLM API key<input type="password" placeholder={has[s.llmProvider]?'Saved securely':'Enter API key'} value={llmKey} onChange={e=>setLlmKey(e.target.value)}/></label><div className="settingActions"><button onClick={save}>Save</button><button onClick={testLLM}>Test LLM</button></div><div className="status">LLM: {status.llm?.status|| (has[s.llmProvider]?'saved':'not configured')} {status.llm?.message||''}</div><hr/><h4>Speech</h4><label>STT model (OpenAI)<input value={s.sttModel} onChange={e=>setS({...s,sttModel:e.target.value})}/></label><label>TTS provider<select value={s.ttsProvider} onChange={e=>setS({...s,ttsProvider:e.target.value})}><option value="openai">OpenAI TTS</option><option value="azure">Azure Speech</option></select></label>{s.ttsProvider==='openai'?<><label>TTS model<input value={s.tts.model||''} onChange={e=>setS({...s,tts:{...s.tts,model:e.target.value}})}/></label><label>TTS voice<input value={s.tts.voice||''} onChange={e=>setS({...s,tts:{...s.tts,voice:e.target.value}})}/></label><label>TTS API key<input type="password" placeholder={has.openai?'Saved securely':'Uses OpenAI key'} value={ttsKey} onChange={e=>setTtsKey(e.target.value)}/></label></>:<><label>Azure region<input value={s.tts.region||''} onChange={e=>setS({...s,tts:{...s.tts,region:e.target.value}})}/></label><label>Azure voice<input value={s.tts.voice||''} onChange={e=>setS({...s,tts:{...s.tts,voice:e.target.value}})}/></label><label>Azure key<input type="password" placeholder={has.azure?'Saved securely':'Enter Azure Speech key'} value={ttsKey} onChange={e=>setTtsKey(e.target.value)}/></label>}<div className="settingActions"><button onClick={testTTS}>Test TTS</button></div><div className="status">TTS: {status.tts?.status||'not tested'} {status.tts?.message||''}</div><label>Language<input value={s.language} onChange={e=>setS({...s,language:e.target.value})}/></label><label><input type="checkbox" checked={s.alwaysListening} onChange={e=>setS({...s,alwaysListening:e.target.checked})}/> Always listen</label><button onClick={async()=>{await save();setOpen(false)}}>Save & close</button></div>}</>}